version: '3.8'

services:
  postgres:
    user: root
    image: postgres:13
    container_name: my_postgres
    ports:
      - "59502:5432"  # HostPort:ContainerPort
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example  # Change this!
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "59503:80"  # Access pgAdmin at http://localhost:59503
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin  # Change this!
    depends_on:
      - postgres

volumes:
  postgres_data:
