col_names:
   "4" : "sourceNo"
   "Family" : "family"
   "Genus" : "genus"
   "Japanese name" : "japName"
   "KYOw No." : "specimenNo_old"
   "Order" : "order_old"
   "Section" : "section_drop"
   "Species" : "species_todo"
   "Subgenus" : "subgenus_drop"
   'anatomy1' : "anatomy1_DS04"
   "evergreen/deciduous" : "anatomy2_DS04"
   "other No." : "otherNo_drop"
   "prep No." : "prepNo_drop"
   "sampling point" : "samplingPoint"  
   "subspecies/variation/forma" : "subspecies_drop"
   "sugiyama_2020" : "citeKey"
   "individuals" : "individuals_drop"
   "n_individuals" : "n_individuals_drop"
   "path" : "source_UUID"