woodType:
  Abietaceae: Softwood
  Aceraceae: Hardwood
  Anacardiaceae: Hardwood
  Annonaceae: Hardwood
  Apocynaceae: Hardwood
  Araucariaceae: Softwood
  Atherospermataceae: Hardwood
  Betulaceae: Hardwood
  Bignoniaceae: Hardwood
  Boraginaceae: Hardwood
  Burseraceae: Hardwood
  Caesalpiniaceae: Hardwood
  Calophyllaceae: Hardwood
  Cannabaceae: Hardwood
  Caryocaraceae: Hardwood
  Celtidaceae: Hardwood
  Cephalotaxaceae: Softwood
  Chloranthaceae: Hardwood
  Clusiaceae: Hardwood
  Combretaceae: Hardwood
  Cornaceae: Hardwood
  Cryptomerieae: Softwood
  Cupressaceae: Softwood
  Dacrydiaceae: Softwood
  Dipterocarpaceae: Hardwood
  Ebenaceae: Hardwood
  Ephedraceae: Softwood
  Euphorbiaceae: Hardwood
  Fabaceae: Hardwood
  Fagaceae: Hardwood
  Ginkgoaceae: Softwood
  Guttiferae: Hardwood
  Irvingiaceae: Hardwood
  Juglandaceae: Hardwood
  Juniperaceae: Softwood
  Lamiaceae: Hardwood
  Laricaceae: Softwood
  Lauraceae: Hardwood
  Lecythidaceae: Hardwood
  Magnoliaceae: Hardwood
  Malvaceae: Hardwood
  Meliaceae: Hardwood
  Mimosoideae: Hardwood
  Moraceae: Hardwood
  Myristicaceae: Hardwood
  Myrsinaceae: Hardwood
  Myrtaceae: Hardwood
  Nyssaceae: Hardwood
  Ochnaceae: Hardwood
  Olacaceae: Hardwood
  Oleaceae: Hardwood
  Phyllocladaceae: Softwood
  Piceaceae: Softwood
  Pinaceae: Softwood
  Platanaceae: Hardwood
  Podocarpaceae: Softwood
  Proteaceae: Hardwood
  Pseudotsugaceae: Softwood
  Putranjavaceae: Hardwood
  Rhamnaceae: Hardwood
  Rosaceae: Hardwood
  Rubiaceae: Hardwood
  Rutaceae: Hardwood
  Salicaceae: Hardwood
  Santalaceae: Hardwood
  Sapindaceae: Hardwood
  Sapotaceae: Hardwood
  Sequoiaceae: Softwood
  Taxaceae: Softwood
  Taxodiaceae: Softwood
  Tectonaceae: Hardwood
  Thujoideae: Softwood
  Tiliaceae: Hardwood
  Torreyiaceae: Softwood
  Tsugaceae: Softwood
  Ulmaceae: Hardwood
  Urticaceae: Hardwood
  Verbenaceae: Hardwood
  Vochysiaceae: Hardwood
